# 1. nekomisystems.com
server {
    listen 8080;
    server_name nekomisystems.com localhost 127.0.0.1;

    root /usr/share/nginx/html; # Raíz de dist/
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

# 1. Subdominio DEV
server {
    listen 8080;
    server_name dev.nekomisystems.com dev.localhost;

    root /usr/share/nginx/html/dev;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Redirecciona las peticiones de /assets a la raíz compartida de dist/
    location /assets/ {
        alias /usr/share/nginx/html/assets/;
    }

    location /wallpapers/ {
        alias /usr/share/nginx/html/wallpapers/;
    }
}

# 2. Subdominio PORTFOLIO
server {
    listen 8080;
    server_name portfolio.nekomisystems.com portfolio.localhost;

    root /usr/share/nginx/html/portfolio;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Redirecciona las peticiones de /assets a la raíz compartida de dist/
    location /assets/ {
        alias /usr/share/nginx/html/assets/;
    }

    location /wallpapers/ {
        alias /usr/share/nginx/html/wallpapers/;
    }

    location /frost-os{
        alias /usr/share/nginx/html/frost-os/;
        index index.html;
        try_files $uri $uri/ /frost-os/index.html;
    }

    location /mikurig{
        alias /usr/share/nginx/html/mikurig/;
        index index.html;
        try_files $uri $uri/ /mikurig/index.html;
    }

    location /manga_reader{
        alias /usr/share/nginx/html/manga_reader/;
        index index.html;
        try_files $uri $uri/ /manga_reader/index.html;
    }

    location /bibootaxgame{
        alias /usr/share/nginx/html/bibootaxgame/;
        index index.html;
        try_files $uri $uri/ /bibootaxgame/index.html;
    }
}