server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Módulo Raíz (nekomisystems.com)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Módulo Landing (dev.nekomisystems.com o nekomisystems.com/landing)
    location /landing/ {
        try_files $uri $uri/ /landing/index.html;
    }

    # Módulo Frost OS
    location /frost-os/ {
        try_files $uri $uri/ /frost-os/index.html;
    }

    # Módulo Manga Reader
    location /manga_reader/ {
        try_files $uri $uri/ /manga_reader/index.html;
    }

    # Módulo Doom Game
    location /doomgame/ {
        try_files $uri $uri/ /doomgame/index.html;
    }

    # Módulo Mikurig
    location /mikurig/ {
        try_files $uri $uri/ /mikurig/index.html;
    }

    # Módulo Bibootaxgame
    location /bibootaxgame/ {
        try_files $uri $uri/ /bibootaxgame/index.html;
    }

    # Caché optimizada para los archivos JS, CSS e imágenes de Vite
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}